"use strict";
console.log('Shahzaib');
console.log('\t Shahzaib');
console.log('Shahzaib1');
console.log('\t Shahzaib \t');
console.log('Shahzaib2');
console.log('\n Shahzaib');
console.log('Shahzaib3');
console.log('\n Shahzaib \n');
console.log('Shahzaib4');
console.log('\t Shahzaib \n');
console.log('Shahzaib5');
console.log('\n Shahzaib \t');
console.log('Shahzaib6');
